server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mallsystem?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  mvc:
    view:
      prefix: /templates/
      suffix: .html



