#端口号
server:
  port: 8081

#mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mallsystem?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

#访问html
  mvc:
    view:
      prefix: /templates/
      suffix: .html

  #redis
  redis:
    database: 0
    database1: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-wait: -1
        max-active: 8
        max-idle: 8
        min-idle: 0

#mybatis
mybatis:
  type-aliases-package: com.miao.entity
  mapper-locations: classpath:mapper/*.xml
  check-config-location: true

#log4j
logging:
  file: ./logs/mallsystem.log
  level:
    com.miao.mapper: debug

